name: codereader
description: Two-dimensional code Reader

publish_to: "none"

version: 1.1.1+3

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  mobile_scanner:
    git:
      url: https://github.com/yuchan2215/mobile_scanner
  sliding_up_panel: ^2.0.0
  permission_handler: ^9.2.0
  mono_kit: ^0.27.1
  url_launcher: ^6.1.2
  image_picker: ^0.8.5+3
  after_layout: ^1.2.0
  intl: ^0.17.0
  share_plus: ^6.3.1
  map_launcher: ^2.2.3
  add_2_calendar: ^2.1.3
  kotlin_flavor: ^0.2.0
  wifi_iot: ^0.3.16
  flutter_contacts: ^1.1.4
  package_info_plus: ^1.4.2
  shared_preferences: ^2.0.15
  awesome_select: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: '#a0e5f7'
  adaptive_icon_foreground: 'assets/icon/icon_foreground.png'
